// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

part of 'services.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC19HZvt_H9XvTH9RoWUJ7eBUgfzflFKHU',
    appId: '1:297630927350:web:38a62ae6de07b6040e5fd7',
    messagingSenderId: '297630927350',
    projectId: 'plpp-10f00',
    authDomain: 'plpp-10f00.firebaseapp.com',
    storageBucket: 'plpp-10f00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdt540Cw24hgCxnG3LcLmWmgkwkrhCds4',
    appId: '1:297630927350:android:9936e86a039d5a110e5fd7',
    messagingSenderId: '297630927350',
    projectId: 'plpp-10f00',
    storageBucket: 'plpp-10f00.firebasestorage.app',
  );
}
